# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Lowkey"
license = "MIT"
licenselink = "https://iamnaran.github.io/"
description = "Lowkey Hugo theme is a simple and modern theme that is inspired by Adam Wathan's Blog."
homepage = "https://iamnaran.github.io/"
demosite = "https://iamnaran.github.io/"
tags = ["simple", "minimal", "responsive", "blog", "personal", "light"]
features = [
  "responsive",
  "single-column",
  "blog",
  "tailwindcss",
]
min_version = "0.110.0"

[author]
  name = "Narayan Panthi"
  homepage = "https://iamnaran.github.io/"
