name = "NaTheme"
license = "GPL-3.0"
licenselink = ""
description = "NaTheme's Style Theme"
homepage = ""
demosite = ""
tags = ["NaRan","NarayanPanthi", "android", "nepal", "dark"]
features = ["blog", "android", "jetpack"]
[author]
  name = "Naryan Panthi"
  homepage = "https://github.com/iamnaran"
[original]
  name = "austin2035"
  homepage = "https://astro.yufengbiji.com/"
  repo = "https://github.com/austin2035/astro-air-blog"
[module]
  [module.hugoVersion]
    min = "0.93.0"
